### PR TITLE
Move DeleteLocalFolderRecursivelyAndWait to utils

### PR DESCRIPTION
**Pull request by EamonNerbonne**
...so I can use it in progress.

(was in packager)

### CODE REVIEW

**Review by PatrickRUG — APPROVED** [review]
Een copy dus?

**Comment by chrarnoldus** [comment]
Er zijn meningen die beweren dat dit gedrag veranderd is: https://stackoverflow.com/questions/60424732/did-the-behaviour-of-deleted-files-open-with-fileshare-delete-change-on-windows/60512798

**Comment by EamonNerbonne** [comment]
heu, interssant.

**Comment by EamonNerbonne** [comment]
@chrarnoldus hoe ben je daar overheen gestruikeld?

**Comment by EamonNerbonne** [comment]
https://github.com/dotnet/runtime/issues/27958 certainly seems to back up this sneaky change...

**Pull request merged**
