### PR TITLE
Allow mapping by constructor args

### PR DESCRIPTION
**Pull request by EamonNerbonne**
So records with non-nullable properties are workable

depends on <s>#471</s> and <s>#470</s>

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
Perf vrijwel onveranderd, mogelijk heel klein beetje trager, maar nog steeds prima, uitkomst playground/EntityFrameworkBenchmark:


<pre><code>
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.508 (2004/?/20H1)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.1.402
  [Host] : .NET Core 3.1.8 (CoreCLR 4.700.20.41105, CoreFX 4.700.20.41903), X64 RyuJIT
</code></pre>
<pre><code>Job=InProcess  MaxRelativeError=0.005  OutlierMode=DontRemove  
Toolchain=InProcessNoEmitToolchain  IterationCount=15  LaunchCount=1  
MaxIterationCount=1000  WarmupCount=2  
</code></pre>

<table>
<thead><tr><th>                                                         Method</th><th>  Mean</th><th>Error</th><th>StdDev</th><th>Gen 0</th><th>Gen 1</th><th>Gen 2</th><th>Allocated</th>
</tr>
</thead><tbody><tr><td>ByColumn_alle_studenten</td><td>15,871.99 μs</td><td>249.777 μs</td><td>233.641 μs</td><td>593.7500</td><td>281.2500</td><td>-</td><td>3729522 B</td>
</tr><tr><td>Dapper_alle_studenten</td><td>19,982.93 μs</td><td>203.726 μs</td><td>190.565 μs</td><td>843.7500</td><td>343.7500</td><td>31.2500</td><td>5199560 B</td>
</tr><tr><td>SQL_alle_studenten</td><td>15,040.28 μs</td><td>136.294 μs</td><td>127.489 μs</td><td>593.7500</td><td>234.3750</td><td>-</td><td>3729344 B</td>
</tr><tr><td>EF_alle_studenten</td><td>17,087.60 μs</td><td>66.148 μs</td><td>61.874 μs</td><td>750.0000</td><td>312.5000</td><td>-</td><td>4778600 B</td>
</tr><tr><td>Dapper_alle_accounts</td><td>2,011.29 μs</td><td>27.561 μs</td><td>25.781 μs</td><td>328.1250</td><td>85.9375</td><td>15.6250</td><td>2147048 B</td>
</tr><tr><td>SQL_alle_accounts</td><td>1,615.58 μs</td><td>11.318 μs</td><td>10.587 μs</td><td>167.9688</td><td>46.8750</td><td>7.8125</td><td>1102892 B</td>
</tr><tr><td>EF_alle_accounts</td><td>2,013.16 μs</td><td>27.911 μs</td><td>26.108 μs</td><td>332.0313</td><td>78.1250</td><td>15.6250</td><td>2185468 B</td>
</tr><tr><td>ByColumn_alle_FinancieelBankRekening</td><td>382.32 μs</td><td>6.388 μs</td><td>5.975 μs</td><td>10.2539</td><td>1.9531</td><td>-</td><td>64640 B</td>
</tr><tr><td>SQL_alle_FinancieelBankRekening</td><td>380.91 μs</td><td>5.537 μs</td><td>5.179 μs</td><td>10.2539</td><td>1.9531</td><td>-</td><td>64632 B</td>
</tr><tr><td>Dapper_alle_FinancieelBankRekening</td><td>NA</td><td>NA</td><td>NA</td><td>-</td><td>-</td><td>-</td><td>-</td>
</tr><tr><td>EF_alle_FinancieelBankRekening</td><td>467.22 μs</td><td>1.074 μs</td><td>1.004 μs</td><td>23.4375</td><td>5.3711</td><td>-</td><td>148560 B</td>
</tr><tr><td>ByColumn_1_student</td><td>71.73 μs</td><td>0.946 μs</td><td>0.885 μs</td><td>2.4414</td><td>0.1221</td><td>-</td><td>15568 B</td>
</tr><tr><td>EF_1_student</td><td>108.77 μs</td><td>0.268 μs</td><td>0.250 μs</td><td>4.7607</td><td>0.2441</td><td>-</td><td>30303 B</td>
</tr><tr><td>EF_1_student_compiled</td><td>81.74 μs</td><td>0.573 μs</td><td>0.536 μs</td><td>3.6621</td><td>0.1221</td><td>-</td><td>23200 B</td>
</tr><tr><td>SQL_1_student</td><td>66.53 μs</td><td>1.147 μs</td><td>1.073 μs</td><td>2.1973</td><td>-</td><td>-</td><td>14128 B</td>
</tr><tr><td>Dapper_1_student</td><td>67.17 μs</td><td>1.162 μs</td><td>1.087 μs</td><td>2.5635</td><td>0.1221</td><td>-</td><td>16600 B</td>
</tr><tr><td>SafeSql_SimplifiedExamenDataSource_1_student_without_nested_query</td><td>69.71 μs</td><td>0.486 μs</td><td>0.455 μs</td><td>0.4883</td><td>-</td><td>-</td><td>3360 B</td>
</tr><tr><td>EF_SimplifiedExamenDataSource_1_student_without_nested_query</td><td>212.80 μs</td><td>4.860 μs</td><td>4.546 μs</td><td>14.6484</td><td>0.4883</td><td>-</td><td>93254 B</td>
</tr><tr><td>EF_SimplifiedExamenDataSource_1_student_without_nested_query_compiled</td><td>90.93 μs</td><td>5.273 μs</td><td>4.932 μs</td><td>1.8311</td><td>-</td><td>-</td><td>12048 B</td>
</tr></tbody></table>

**Comment by EamonNerbonne** [comment]
*ping*

**Review by fdij — APPROVED** [review]
Beetje veel en ingewikkeld te reviewen, maar de testen zien er goed uit.

**Comment by EamonNerbonne** [comment]
https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/472/files#diff-acbcf6890684c216417f676a9b952f0da8ef98b66141446bb26aaade2c1e1752R323

Deze method is de hart van de zaak, en geheel nieuw.

**Review by Bazeloth — APPROVED** [review]

**Pull request merged**
